global:
  message: Welcome to Microservices Environment!
logging:
  level:
    root: INFO
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
